### ISSUE TITLE
Please install 'terminal-notifier' or 'ruby-gntp'

### ISSUE THREAD

**Issue by sivabudh** [janlelis/irbtools#28]
I just finished installing irbtools and added require 'irbtools' in ~/.irbrc. However, when I launch irb, I'm greeted with this warning:

http://cl.ly/image/0S1Y431B2u3i

Even though I already have `terminal-notifier` installed. What gives?

**Comment by janlelis** [comment]
Hi @sivabudh,

sorry for the late answer. This might be unrelated to irbtools. Can you please paste your whole .irbrc file and the ruby version you are using!

**Comment by janlelis** [comment]
Closing. Please re-open with more information if this is still a problem for you.

**Comment by sivabudh** [comment]
Hi @janlelis thanks for getting back to me. I don't have this problem anymore. #Ruby2.2.3 #RVM.
