### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by ghost** [janlelis/irbtools#32]
require 'irbtools'
fatal: No live threads left. Deadlock?
        from /usr/lib/ruby/gems/2.2.0/gems/irbtools-2.0.0/lib/irbtools.rb:48:in `join'
        from /usr/lib/ruby/gems/2.2.0/gems/irbtools-2.0.0/lib/irbtools.rb:48:in`map'
        from /usr/lib/ruby/gems/2.2.0/gems/irbtools-2.0.0/lib/irbtools.rb:48:in `<top (required)>'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in`require'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in`require'
        from (irb):4
        from /usr/bin/irb:11:in `<main>'

require 'irbtools'

Hmm. Latest ruby version here.
Not sure why I get this error in irb when I type that require.

Perhaps the message could be more indicative of what the problem is? I am not sure what live threads the message is talking about; all I tried was a require 'irbtools'

regards

**Comment by janlelis** [comment]
Thanks for the report. There must be a bug in the loading mechanism of irbtools, which uses threads for faster loading. Does requiring irbtools always lead to this error, or only sometimes? Does `irb -f -r irbtools' work?

**Comment by slbug** [comment]
same issue here. irb -f -r irbtools does not work too.

**Comment by janlelis** [comment]
Hey @shevegen and @slbug 

Does this still happen with recent versions of Rails and irbtools?

**Comment by janlelis** [comment]
Closing, please re-open if you still experience this problem…
