### ISSUE TITLE
gem 'cd' dependency

### ISSUE THREAD

**Issue by DoctorRu** [janlelis/irbtools#35]
"Gem::InstallError: cd requires Ruby version ~> 2.0.
An error occurred while installing cd (1.0.0), and Bundler cannot continue.
Make sure that `gem install cd -v '1.0.0'` succeeds before bundling."

How to run irbtools again with ruby 1.9.3?

**Comment by janlelis** [comment]
Ruby 1.9.3 is a legacy Ruby: https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/. Irbtools and its sub-components (e.g. Wirb) will not implement workarounds for Ruby < 2.

If you are stuck on 1.9 for some reason, you will need to use irbtools version 1.7.1.
