### ISSUE TITLE
Reload hangs after exception in Rails console

### ISSUE THREAD

**Issue by codehugger** [janlelis/irbtools#36]
This happens consistently when errors occur in Rails code. To reproduce put the following code in e.g. a model class.

``` ruby
def self.cause_error
    1/0
end
```

Then run it, watch it fail and then call reload!

``` bash
>> MyModel.cause_error
ZeroDivisionError: divided by 0
...
>> reload!
Reloading...
```

and watch it hang for eternity. The only work-around I have found is to restart the Rails console completely.

**Comment by janlelis** [comment]
Hey @codehugger!

Does this still happen with recent versions of Rails and irbtools?
