### ISSUE TITLE
cannot load such file -- irbtools/more

### ISSUE THREAD

**Issue by mr-pug** [janlelis/irbtools#37]
When I include `require 'irbtools/more'` in `~/.irbrc`, I get the error:
`cannot load such file -- irbtools/more`

It seems to load up without `/more`. I have `irbtools` installed at `~/.rvm//gems/ruby-2.2.3/gems/irbtools-2.0.1`.

**Comment by janlelis** [comment]
Hi, make sure you have the following line in your `Gemfile`:

```ruby
gem "irbtools-more", require: 'irbtools/binding'
```

**Comment by janlelis** [comment]
Closing (please re-open if you still experience this problem)
