### ISSUE TITLE
Documentation/Explanation for irbtools (colourized return values)

### ISSUE THREAD

**Issue by ghost** [janlelis/irbtools#43]
Hello Jan,

First, props for irbtools - it's pretty nifty, although I have just started with it so I am not
really qualified to comment as how great it is since ... I don't yet know all about it.

Anyway, when I type the following:

**3+3**

I get this:

    3+3 #=> 6

So far so fine. The part starting at '#' is actually **colourized**, which is neat.

I actually did not know that this can be colourized.

If you happen to have a bit of time in the future, do you think you can add some explanation
as to how this colourization is (a) done and (b) could be changed by the end user?

(1) The colours are nice but I want to experiment a little with the "classical" html colours
such as slateblue, royalblue etc. (e. g. with their R G B values http://www.tayloredmktg.com/rgb/),
mostly because I usually use a dark blackground for terminals, but sometimes I may have
to use a white background, such as in a restriction university environment where I can only
start a pre-defined xterm that has a white background (perhaps you know some of these
weird university environments ... like kiosk-mode in some departments of a university).

Perhaps it is either wirb or fancy_irb but right now I do not know. I know wirb a little bit
from years ago; have never seen fancy_irb yet though.

(2) Perhaps the file at https://github.com/janlelis/irbtools/blob/master/CONFIGURE.md
could also include a short subsection about colours/colourizing irbtools, including one
or two example?

Anyway, please do feel free to close this issue request at any moment in time, and best
of luck for irbtools - I think it is great that, aside from pry, we get to have more options
in general to improve on "oldschool" commandline/REPL stuff. (pry is fine too but it
is somewhat different from irb, and my own irbrc is actually VERY simple ... almost 
barebones. I love simplicity, but I also like colours.)

**Comment by janlelis** [comment]
Terminal colors & customization are provided by [wirb](https://github.com/janlelis/wirb), [fancy_irb](https://github.com/janlelis/fancy_irb), and [paint](https://github.com/janlelis/paint).

Feel free to open a PR which adds examples of customization to [CONFIGURE.md](https://github.com/janlelis/irbtools/blob/master/CONFIGURE.md)
