### ISSUE TITLE
WARN: Unresolved or ambiguous specs during Gem::Specification.reset:

### ISSUE THREAD

**Issue by JoeDupuis** [janlelis/irbtools#45]
I get

```
WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
      reline (>= 0)
      Available/installed versions of this gem:
      - 0.1.3
      - 0.1.2
WARN: Clearing out unresolved specs. Try 'gem cleanup <gem>'
Please report a bug if this causes problems.
```

after installing version 3.0.2 on 
ruby 2.7 
rails 6.0.2.1 
when running bundler.  

Any idea what could cause this?

**Comment by janlelis** [comment]
No real idea, but maybe https://stackoverflow.com/questions/17936340/unresolved-specs-during-gemspecification-reset/18127613#18127613 or https://github.com/rubygems/rubygems/issues/1070 or https://github.com/rubygems/rubygems/issues/1945 can help?

**Comment by JoeDupuis** [comment]
Cleanup does not help, but I figured out that there is a version of reline installed

**Comment by JoeDupuis** [comment]
Updating bundler from 2.0.1 to 2.1.4 fixed it.

**Comment by janlelis** [comment]
Thank you for figuring this out -- might be helpful for others with the same problem
