### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by gsbhasin123** [janlelis/irbtools#46]
Example: allow user to have
```
>> # code
=>  return value
```
Instead of
``` 
>> # code # => return value
```
allowing changing the prompt (eg say you want `> ` or `>>> ` or the irb default) would also be a big plus!

**Comment by janlelis** [comment]
Hi @gsbhasin123,

thank your for your feedback. The two above things are already configurable, although this is not obvious from the Irbtools documentation. I have extended the CONFIGURE.md file to show how to achieve this: https://github.com/janlelis/irbtools/commit/ec1e89f923487bc5b01836c74a2ddf647e8364a9

**Comment by gsbhasin123** [comment]
Awesome!
