### ISSUE TITLE
Can't install irbtools-more due to drx gem 

### ISSUE THREAD

**Issue by foreverLoveWisdom** [janlelis/irbtools#47]
I want to use `irbtools-more` for my irb session. However, the gem depends on `drx` which is not supported for Ruby > 2.0 (https://github.com/mooffie/drx/issues/6)
Is there a way for me to skip the gem `drx` so that I can still use `irbtools-more`?

**Comment by janlelis** [comment]
Hey there, please make sure you are using the newest versions of `irbtools` and `irbtools-more` - it should work since `drx` was dropped a long time ago
