### ISSUE TITLE
Support for Ruby 3.0.0

### ISSUE THREAD

**Issue by kapso** [janlelis/irbtools#49]
Adding a request for Ruby `3.0.0` support.

```
code-0.9.2 requires ruby version ~> 2.0, which is incompatible with the current version, ruby 3.0.0p0
```

**Comment by janlelis** [comment]
Thank you for reporting the issue!

I have released new versions of the gems in question, which had the overly restricted Ruby version requirement, so it should work now.

Please try installing irbtools again with: `gem install irbtools:3.0.4`

**Comment by kapso** [comment]
thanks
