### ISSUE TITLE
binding_of_caller dependency

### ISSUE THREAD

**Issue by kapso** [janlelis/irbtools#50]
Any plans for upgrading this dependency. `binding_of_caller 1.0.0` has support for Ruby 3.0.0

```
irbtools-more (= 2.4.1) x86_64-darwin-20 was resolved to 2.4.1, which depends on
      binding_of_caller (~> 0.8)
```

**Comment by janlelis** [comment]
Hi @kapso - irbtools-more 2.5.0 is now released! Thanks for the pull requests!
