### ISSUE TITLE
irbtools triggers "irb: warn: can't alias ls from irb_ls" in Ruby 3.0.2

### ISSUE THREAD

**Issue by todd-a-jacobs** [janlelis/irbtools#53]
When running irb with either the irbtools or irbtools-more gem loaded, I get the following error in Ruby 3.0.2:

```
$ irb
Welcome to IRB. You are using ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin20]. Have fun ;)
irb: warn: can't alias ls from irb_ls.
>> 
```

This error does not occur on Ruby 2.7.2, so I suspect it's an incompatibility with the new core irb code that's at issue. My ~/.irbrc is pretty simple:

```
IRB.conf[:PROMPT][:DEFAULT][:RETURN].prepend ?#
require 'irbtools/more'
```

Please note that I also tried it with just `require 'irbtools'` but had exactly the same result in Ruby 3.0.2. Ruby 2.7.2 started cleanly, but instead reported "Bond has detected EditLine and may not work with it. See the README's Limitations section." when switching to irbtools-more.

For 3.0.2, I took a look at the irbtools code base, and can't figure out where the alias warning is coming from. I'd happily customize #irb_ls to something like `ils` if I could figure out where it was being defined. I couldn't find it in lib/irbtools/binding.rb, so I'm not sure where the conflict is coming from. Calling `show_source "irb_ls"` shows:

``` ruby
>> show_source "irb_ls" #=> nil

From: $HOME/.gem/ruby/3.0.2/gems/irb-1.3.7/lib/irb/extend-command.rb:189

          def #{cmd_name}(*opts#{kwargs}, &b)
            require "#{load_file}"
            arity = ExtendCommand::#{cmd_class}.instance_method(:execute).arity
            args = (1..(arity < 0 ? ~arity : arity)).map {|i| "arg" + i.to_s }
            args << "*opts#{kwargs}" if arity < 0
```

so #irb_ls is clearly being set by irb itself, but where is irbtools-more (or its dependencies) trying to alias it?

**Comment by janlelis** [comment]
@todd-a-jacobs Hi there, thanks for reporting this.

The problem is that IRB now has a `ls` method (for listing things), but Irbtools already has another `ls` for listing directory contents, hence the warning. I followed your suggestion and renamed the `irb_ls` alias to `ils`.
