### ISSUE TITLE
irb version 1.13.1 has been released, which conflicts with irbtools 4.0.9 due to the version restriction.

### ISSUE THREAD

**Issue by nogweii** [janlelis/irbtools#57]
As per the title. I don't believe there are any actual code conflicts, so expanding the version range should suffice.

I don't know how risky this would be, but does it make sense to expand the version constraint to only cover the major version rather than major+minor?

**Comment by awilliams000** [comment]
> As per the title. I don't believe there are any actual code conflicts, so expanding the version range should suffice.
> 
> I don't know how risky this would be, but does it make sense to expand the version constraint to only cover the major version rather than major+minor?

Same is true for irb 1.13.2 with ruby 3.3.3. The proposed fix would be nice.

**Comment by janlelis** [comment]
Thanks for your reports, I'll take a look within the next days

**Comment by nogweii** [comment]
Ah, irb [v1.14.0](https://github.com/ruby/irb/releases/tag/v1.14.0) has been recently released a couple of days ago. Could you do another update? :sweat_smile:
